import { type ConfigPlugin, withGradleProperties, createRunOncePlugin } from '@expo/config-plugins'

/**
 * Raise the Gradle daemon JVM heap so memory-hungry post-compile tasks
 * (notably AGP's `compileReleaseArtProfile`) don't OOM on CI.
 *
 * Background: the `v4.5.8-beta` tagged build failed with
 *   Execution failed for task ':app:compileReleaseArtProfile'.
 *     > Java heap space
 * every compile/dex step had already succeeded — the Gradle daemon simply
 * ran out of heap. Expo's default `org.gradle.jvmargs=-Xmx2048m` is too
 * tight for a multi-ABI release build; 4 GB is the standard headroom.
 *
 * `android/gradle.properties` is regenerated by `expo prebuild`, so the
 * value must be set here (a config plugin) to persist across prebuilds.
 */
const withGradleHeap: ConfigPlugin = (config) => {
  return withGradleProperties(config, (props) => {
    const KEY = 'org.gradle.jvmargs'
    props.modResults = props.modResults.map((entry) => {
      if (entry.type === 'property' && entry.key === KEY) {
        // -Xmx2048m -> -Xmx4096m ; keep MaxMetaspaceSize as-is.
        entry.value = entry.value.replace(/-Xmx\d+[mMgG]/, '-Xmx4096m')
      }
      return entry
    })
    return props
  })
}

export default createRunOncePlugin(withGradleHeap, 'with-gradle-heap', '1.0.0')
